config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :questions
  resources :users
  
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

end

app/models/question.rb
class Question < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  # attr_accessible :email, :password
  # validates_uniquesness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate
  	if not current_user
  		redirect_to signin_path, notice: 'Not signed in'
  	end
  end

  helper_method :current_user

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate, :except => [:show, :index]

  skip_before_filter  :verify_authenticity_token

  def index
    @questions = Question.all
    render json: { questions: @questions }.to_json
  end

  def show
    @question = Question.find(params[:id])
    render json: @question.to_json
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:correct, :question, :answer)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = 'Denied mother...'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @questions = Question.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Golden</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="icon" href="assets/favicon-golden.png" type="image/x-icon"/>

    <script src="https://fb.me/react-with-addons-0.13.3.js"></script>
    <script src="https://fb.me/JSXTransformer-0.13.3.js"></script>
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<div class="col-5-5">
  <h2><%= @question.question %></h2>
  <div id="content" class="black">
    <p><%= @question.answer %></p>
  <%= form_for @question do |f| %>
      <%= f.text_field :question %><br>
      <%= f.text_field :answer %><br>
      <%= f.text_field :correct %><br>
      <%= f.submit %>
  <% end %>
  </div>

</div>

app/views/welcome/index.html.erb
<div class="col-5-5">
  <h2>Golden Questions</h2>
  <div id="content" class="black">
    <% @questions.each do |question| %>
      <p class="q-margin"><%= link_to "#{question.question}", edit_question_path(question) %></p>
    <% end %>
  </div>
</div>